name: Ejecutar comandos Laravel y desplegar con FTP

on: 
  pull_request:
    types: [closed]
        
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Docker
      uses: docker/setup-buildx-action@v2.5.0

    - name: Build Docker Image
      run: docker build -t myapp .
      
    - name: Rename the docker image
      run: docker run -d --name myapp myapp
      
    - name: Export compiled assets
      run: docker cp myapp:/app/. .

    - name: Deploy with FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/
        delete-removed: true
        exclude: |
          **/.vscode/*
          **/README.md
          **/TODO.drawio
          **/.git*
          **/.git*/**
          **/node_modules/**
          deploy.sh
