name: Ejecutar comandos Laravel y desplegar con FTP

on: 
  pull_request:
    types: [closed]
        
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Docker
      uses: docker/setup-buildx-action@v2.5.0

    - name: Build Docker Image
      run: docker build -t myapp .

    - name: Install Dependencies
      run: docker run --rm -v $PWD:/app -w /app myapp composer install --no-interaction --no-progress --prefer-dist

    - name: Clear Laravel Cache
      run: docker run --rm -v $PWD:/app -w /app myapp php artisan cache:clear

    - name: Clear Laravel Config Cache
      run: docker run --rm -v $PWD:/app -w /app myapp php artisan config:clear

    - name: Generate Laravel Mix
      run: docker run --rm -v $PWD:/app -w /app myapp npm run build

    - name: Deploy with FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./public/
        remote-dir: /public_html/
        delete-removed: true
        exclude: |
          **/.vscode/*
          **/README.md
          **/TODO.drawio
          **/.git*
          **/.git*/**
          **/node_modules/**
          deploy.sh
