name: Ejecutar comandos Laravel y desplegar con FTP

on: 
  pull_request:
    types: [closed]
        
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configurar ambiente PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: |
          pdo_sqlite
          sqlite3
          curl
          dom
          mbstring
          zip
          exif
          ffi
    - name: Configurar ambiente Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Instalar dependencias de Composer
      run: composer install
    - name: Limpiar cache de Laravel
      run: php artisan cache:clear
    - name: Limpiar configuración de Laravel
      run: php artisan config:clear
    - name: Instalar dependencias de NPM
      run: npm install
    - name: Compilar assets de Laravel
      run: npm run build
    - name: Desplegar con FTP
      uses: SamKirkland/FTP-Deploy-Action@4.1.1
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html # La carpeta en la que se encuentra tu sitio web en el servidor
        local-dir: ./public # La carpeta donde se encuentran los archivos compilados
        exclude: |
          **/.vscode/*
          **/README.md
          **/TODO.drawio
          **/.git*
          **/.git*/**
          **/node_modules/**
          deploy.sh